{{ $versions := (includeTemplate "versions.tmpl" .) | fromYaml -}}
.oh-my-zsh:
  type: archive
  url: https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz
  exact: true
  stripComponents: 1
  refreshPeriod: 168h
.oh-my-zsh/custom/plugins/zsh-syntax-highlighting:
  type: archive
  url: https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz
  exact: true
  stripComponents: 1
  refreshPeriod: 168h
.local/bin/oh-my-posh:
  type: file
  url: https://github.com/JanDeDobbeleer/oh-my-posh/releases/{{ $versions.oh_my_posh }}/download/posh-linux-amd64
  executable: true
  refreshPeriod: 168h
.local/share/fonts:
  type: archive
  url: https://github.com/ryanoasis/nerd-fonts/releases/{{ $versions.nerd_fonts }}/download/FiraMono.zip
  refreshPeriod: 744h
  include: ["*.otf"]
.local/bin/mise:
  type: file
  url: https://github.com/jdx/mise/releases/download/{{ $versions.mise }}/mise-{{ $versions.mise }}-linux-x64
  executable: true
  refreshPeriod: 168h
